starknetprojects/rwax

src/contracts/realestate.cairo

This commit introduces the create_proposal function to enable secure proposal creation for real-world asset interactions on the RWAX platform.  Closes #5
- Implemented the create_proposal function with authorization checks and event emission.
- Only property managers or shareholders holding more than 10% ownership of a property can create proposals.
-  Each proposal includes:
1. Property ID
2. Description
3. Value and recipient
4. Voting deadline and tracking fields
- Automatically emits a ProposalCreated event for transparency and traceability.
- Resolved trait implementation errors by aligning the function with the contract's interface requirements.

feat: Implemented the create_proposal function

---

src/contracts/realestate.cairo

I have added the functions as instructed.

Added purchase_property

---

src/contracts/realestate.cairo
src/interfaces/irealestate.cairo
src/lib.cairo
src/structs/propertydetails.cairo

Added get_proposal_details function

---

src/contracts/realestate.cairo

Added the cast_vote function to the contract.

Added cast_vote function

---

src/contracts/realestate.cairo

Added distribute_rental_income function

---

src/contracts/realestate.cairo

I've added the create_proposal function

Added create_proposal function

---

.github/workflows/scarb-ci.yml

This PR implements a new GitHub Action workflow that automatically runs `scarb build`, `scarb fmt --check`, and `scarb test` on every push to any branch. This automation ensures code quality and consistency across all contributions without requiring manual intervention from maintainers.
Closes #38
- **Added `.github/workflows/scarb-ci.yml`**: Complete CI workflow configuration
- **Workflow triggers**: Runs on push events to all branches (`**`)
- **Three automated checks**:
- `scarb build` - Ensures code compiles successfully
- `scarb fmt --check` - Validates code formatting standards
- `scarb test` - Runs the full test suite
- Uses `ubuntu-latest` runner for consistent environment
- Leverages `actions/checkout@v4` for repository access
- Utilizes `software-mansion/setup-scarb@v1` for …

GitHub action workflow for scarb build, fmt, and test checks

---

src/events/metal_bulk_sales.cairo
src/events/metal_finance.cairo
src/events/metal_property.cairo
src/events/metal_proposal.cairo
src/events/metal_vote.cairo
src/interfaces/iprecious_metal.cairo
src/lib.cairo
src/structs/metal_property.cairo
src/structs/metal_proposal.cairo

-  I created and update the metal interface
-  Created metal structs in the structs folder
-  Created metal events in the events folder
-  Added the metal interface module in the lib.cairo folder
-  Made sure all the code runs well.

added & updated metal interface

---

src/contracts/precious_metal.cairo
src/events/metal_property.cairo
src/structs/metal_property.cairo

I added the logical to add a precious metal asset to project.

Added metal asset function

---

src/contracts/precious_metal.cairo

This function retrieves the details of the precious metal to be tokenized

added function to get metal assets detail

---

src/contracts/precious_metal.cairo

This function adds update spot price function in the protocol

add update spot price function

---

src/contracts/precious_metal.cairo

This function creates the  physical redemption request

created the request physical redemption functiom

---

src/contracts/precious_metal.cairo

This function distributes storage fee refund in the protocol

added distribute_storage_fee_refund function

---

src/contracts/precious_metal.cairo
src/events/metal_proposal.cairo
src/structs/metal_proposal.cairo

This function Creates metal proposal

Create metal proposal

---

src/contracts/precious_metal.cairo

update readme file

---

contracts/rwa_factory.cairo

covered #63 
kindly look into it

Add skeleton for RWAFactory contract

---

src/structs/asset.cairo

This PR adds the `AssetData` Struct which is pertinent to the rest of the code. Thank you.
Closes #61

Implement AssetData struct

---

src/contracts/rwa_factory.cairo

Closes #78
@GideonBature  please review

Implemented the has_tokenizer_role function

---

.tool-versions
src/contracts/rwa_factory.cairo
src/structs/asset.cairo
tests/test_minimal.cairo
tests/test_tokenize_asset.cairo

Closes #73
This PR implements the core functionality for the RWA (Real World Assets) Factory contract, replacing placeholder implementations with fully functional asset tokenization capabilities.
- **Asset Tokenization**: Complete implementation of `tokenize_asset()` with proper NFT minting and data storage
- **Role-Based Access Control**: Implemented TOKENIZER_ROLE management with grant/revoke functionality
- **Asset Data Management**: Full CRUD operations for asset metadata with proper storage mechanisms
- **Token Counter System**: Automatic token ID generation and tracking
- **AssetTokenized**: Emitted when new assets are successfully tokenized
- **TokenizerRoleGranted**: Emitted when tokenizer permissions are granted
- **TokenizerRoleRevoked**: Emitted when tokenizer permissions are …

feat: Tokenize Asset

---

.tool-versions
Scarb.toml
src/contracts/rwa_factory.cairo
src/lib.cairo

Closes #95
This PR solves the issue of the code not compiling due to incorrect imports and import paths.

Fix compilation problem
